// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIHq5QhnQ4QArpw-OeMKFH8ts0r7bdSc',
    appId: '1:79205110861:web:c2c73e7ece142d40d9b804',
    messagingSenderId: '79205110861',
    projectId: 'gamofest-4b646',
    authDomain: 'gamofest-4b646.firebaseapp.com',
    storageBucket: 'gamofest-4b646.appspot.com',
    measurementId: 'G-7LZMK2NBT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnK4PizGQpouXTLPi8x35uSBN4INrFHpI',
    appId: '1:79205110861:android:5263ba1b2f07fba0d9b804',
    messagingSenderId: '79205110861',
    projectId: 'gamofest-4b646',
    storageBucket: 'gamofest-4b646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGz1XY-7pz42cn6AQa4b4t43clCwT1cHo',
    appId: '1:79205110861:ios:0472740343308552d9b804',
    messagingSenderId: '79205110861',
    projectId: 'gamofest-4b646',
    storageBucket: 'gamofest-4b646.appspot.com',
    iosClientId: '79205110861-q2tt54hsl4a50egb3os9p8o9rid1ah6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamefestival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGz1XY-7pz42cn6AQa4b4t43clCwT1cHo',
    appId: '1:79205110861:ios:0472740343308552d9b804',
    messagingSenderId: '79205110861',
    projectId: 'gamofest-4b646',
    storageBucket: 'gamofest-4b646.appspot.com',
    iosClientId: '79205110861-q2tt54hsl4a50egb3os9p8o9rid1ah6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamefestival',
  );
}
